spring:
  application:
    name: api-user

server:
  port: 6001

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001:7001/eureka/
    register-with-eureka: true
    fetch-registry: true