server:
  port: 6061


spring:
  application:
    name: user
  ###druid数据源配置
  datasource:
    name: dataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/imalvisc?useSSL=false
    username: root
    password: imalvisc
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


###apollo配置
app:
  id: imalvisc
apollo:
  bootstrap:
    enabled: true
    namespaces: application,imalvisc
  meta: http://127.0.0.1:8080
  cacheDir: /data/project/${app.id}/config-cache


###eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001:7001/eureka/
    registrar-with-eureka: true
    fetch-registry: true


###feign配置
feign:
  hystrix:
    enabled: true #开启熔断机制


###hystrix配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000


###Redis配置
redis:
  password:
  port: 6379
  host: 127.0.0.1
  timeout: 5000
  pool:
    maxActive: 10
    maxWait: -1
    maxIdle: 8
    minIdle: 0
    testOnBorrow: true
    testOnReturn: false
    testWhileIdle: true


###mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true


###swagger配置
swagger:
  enable: true
  basePackage: com.imalvisc.user.controller
  title: v1.0用户中心接口文档
  description: v1.0用户中心接口文档
  termsOfServiceUrl: http://localhost:6061/
  version: v1.0
  contact:
    name: 陈嘉明
    url: https://www.baidu.com/
    email: 13570038865@163.com