server:
  port: 6061

spring:
  application:
    name: user
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/imalvisc?useSSL=false
      username: root
      password: imalvisc
      #filters: stat,wall,log4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

###Redis配置
redis:
  password:
  port: 6379
  host: 127.0.0.1
  timeout: 5000
  pool:
    maxActive: 10
    maxWait: -1
    maxIdle: 8
    minIdle: 0
    testOnBorrow: true
    testOnReturn: false
    testWhileIdle: true

mybatis-plus:
  #xml文件路径
  mapper-locations: classpath*:/mapper/*.xml
  #实体包名
  typeAliasesPackage: com.imalvisc.user.model.entity
  global-config:
    db-config:
      #表名前缀
      table-prefix: tb_
      #主键类型 0:数据库ID自增, 1:用户输入ID, 2:全局唯一ID(数字类型唯一ID), 3:全局唯一ID(UUID);
      id-type: 0
      #字段策略 0:忽略判断, 1:非NULL判断, 2:非空判断
      field-strategy: 1
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
  configuration:
    #驼峰下划线转换
    map-underscore-to-camel-case: true
    #日志打印
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


###apollo配置
app:
  id: imalvisc
apollo:
  bootstrap:
    enabled: true
    namespaces: application,imalvisc
  meta: http://127.0.0.1:8080
  cacheDir: /data/project/${app.id}/config-cache


###swagger配置
swagger:
  enable: true
  basePackage: com.imalvisc.user.controller
  title: v1.0用户中心接口文档
  description: v1.0用户中心接口文档
  termsOfServiceUrl: http://localhost:6061/
  version: v1.0
  contact:
    name: 陈嘉明
    url: https://www.baidu.com/
    email: 13570038865@163.com